spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: root
  #    password: ENC(+zKRzzhgWWIR6//bQeyWKA==)
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jasypt:
  encryptor:
    bean: stringEncryptor