spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: root
  #    password: ENC(+zKRzzhgWWIR6//bQeyWKA==)
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

  cache:
    redis:
      time-to-live: 10
      cache-null-values: true

  data:
    redis:
      host: localhost
      port: 6379

jasypt:
  encryptor:
    bean: stringEncryptor
application:
  security:
    jwt:
      secret-key: 45645636454645967asd89as7dqwdqwd788w9f7as4g789as7f49awf7asdfuasdigfniouadsfghweoiaufhsadifhsdiouahfmdsaioufgbadisouyfgsadyfiungsdaew/8f7ae/wf
      expiration: 60000
      refresh-token:
        expiration: 604800000